name: FragMAX
channels:
  - conda-forge
dependencies:
  - python=3.6
  - Django=2.2.1
  - sqlparse=0.3.0
  - natsort=6.0.0
  - matplotlib=3.1.1
  - requests=2.22.0
  - seaborn=0.9.0
  - rdkit=2019.09.3
  - fabio=0.10.2
  - celery=4.3.0
  - redis=5.0.3
  - redis-py=3.3.11
  - pip=20.0.2
  - pycryptodomex=3.9.7
  - pip:
    - django-static-jquery==2.1.4
    - pyfastcopy==1.0.3
    - pypdb==1.300
    - redlock==1.2.0
    - zipstream-new==1.1.7
    - django-material==1.6.7
