name: FragMAX
channels:
  - conda-forge
dependencies:
  - python=3.8.6
  - django=2.2.5
  - natsort=6.0.0
  - requests=2.25.1
  - gemmi=0.4.5
  - rdkit=2019.09.3
  - fabio=0.10.2
  - celery=4.4.6
  - redis=5.0.3
  - redis-py=3.5.2
  - pycryptodomex=3.9.7
  - xmltodict=0.12.0
  - pyyaml==5.4.1
  - pandas=1.2.4
  - pip=20.3.3
  - pip:
    - django-static-jquery==2.1.4
    - pypdb==2.0
    - redlock==1.2.0
    - zipstream-new==1.1.7
    - asyncssh==2.5.0
    - django-material==1.6.7
    - pony==0.7.14
