name: FragMAX
channels:
  - conda-forge
dependencies:
  - python=3.8.6
  - django=3.2.10
  - natsort=6.0.0
  - requests=2.25.1
  - jsonschema=4.4.0
  - gemmi=0.5.7
  - rdkit=2019.09.3
  - fabio=2022.12.1
  - celery=4.4.6
  - redis-server=6.2.6
  - redis-py=3.5.2
  - xmltodict=0.12.0
  - pyyaml==5.4.1
  - pandas=1.5.2
  - asyncssh==2.11.0
  - pip=20.3.3
  - pony=0.7.16
  # for troubleshooting jobds lock-up issue
  - py-spy=0.3.10
  - pip:
    - django-static-jquery==2.1.4
    - pypdb==2.0
    - redlock==1.2.0
    - zipstream-new==1.1.7
    - django-material==1.10.0
