[tool.black]
exclude = '''
(
  #
  # black-list (heh) where we don't enforce black formatting
  #
  # this is mostly old files, which are waiting for one global
  # 'black reformat' commit, try to not add more file to this list
  #
  fragview/auth/__init__.py |
  fragmax/wsgi.py |
  fragmax/urls.py |
  deploy/create_vol.py |
  fragview/auth/ispyb.py |
  fragview/middleware.py |
  fragview/cbf.py |
  fragview/views/download.py |
  manage.py |
  tests/test_auth_ispyb.py |
  tests/test_views_fragment.py |
  tests/test_middleware.py
)
'''

[tool.mypy]
exclude = "worker/data/pandda_prepare_runs.py|fragview/migrations/|static/"

[[tool.mypy.overrides]]
    module = [
        "pony",
        "pony.orm",
        "pypdb",
        "fabio",
        "rdkit",
        "rdkit.Chem",
        "gemmi",
        "fabio.cbfimage",
        "pandas",
        "pandas.errors",
        "celery",
        "django",
        "django.db",
        "django.db.models",
        "django.http",
        "django.conf",
        "django.urls",
        "django.test",
        "django.forms",
        "django.shortcuts",
        "django.test.client",
        "django.core.wsgi",
        "django.views.decorators.csrf",
        "django.contrib.auth.models",
        "django.http.request",
        "django.core.management",
        "django.core.management.base",
        "django.core.files.uploadedfile",
        "natsort",
        "redlock",
        "material.frontend",
        "asyncssh",
        "zipstream",
        "xmltodict",
        "jsonschema",
    ]
    ignore_missing_imports = true
