[tool.black]
exclude = '''
(
  #
  # black-list (heh) where we don't enforce black formatting
  #
  # this is mostly old files, which are waiting for one global
  # 'black reformat' commit, try to not add more file to this list
  #
  fragview/auth/__init__.py |
  fragmax/wsgi.py |
  fragmax/urls.py |
  deploy/create_vol.py |
  fragview/context_processors.py |
  fragmax/settings.py |
  fragview/auth/ispyb.py |
  fragview/autoproc.py |
  fragview/fileio.py |
  fragview/middleware.py |
  fragview/cbf.py |
  fragview/views/crypt.py |
  fragview/views/download.py |
  fragview/views/misc.py |
  fragview/views/reciprocal.py |
  manage.py |
  tests/test_auth_ispyb.py |
  tests/test_views_fragment.py |
  tests/test_worker_cpp4.py |
  tests/test_worker_dials.py |
  worker/__init__.py |
  tests/test_middleware.py
)
'''
