version: "3"
services:
  fragmax:
    image: docker.maxiv.lu.se/fragmax
    container_name: fragmax
    networks:
      - fragmax
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/nslcd.conf:/etc/nslcd.conf
      - /mxn/home:/mxn/home
      - /mxn/groups/biomax:/mxn/groups/biomax
      - /data/visitors/biomax:/data/visitors/biomax
      # for testing
      - /data/staff/biomax:/data/staff/biomax
      # crystal snapshot pictures
      - /data/staff/ispybstorage/pyarch/visitors:/data/staff/ispybstorage/pyarch/visitors
      - fragmax:/volume

volumes:
  fragmax:
    external: true

networks:
  fragmax:
    ipam:
      driver: default
      config:
        # set explicit subnet so that IP-ranges does not
        # collide with MAXIV NFS servers IP-ranges (172.18.0.0)
        - subnet: 172.23.0.1/16
